routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// start is admin
Route::prefix('admin')->name('admin.')->middleware(['is_admin'])->namespace('Admin')->group(function(){
	Route::get('dashboard', 'HomeController@adminHome')->name('home');
	Route::resource('servers','ServersController')->only(['index','store','destroy','update']);
	Route::resource('domains','DomainsController')->only(['index','store','destroy','update']);
	Route::resource('owners','OwnersController')->only(['index','store','destroy','update']);
	Route::get('runcloud','RuncloudController@index');
});
// end is admin

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Domains.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Domains extends Model
{
	protected $table 	= 'domains';
	protected $fillable = ['domain_name','domain_expired','server_id','user_id'];

	public function server()
	{
		return $this->belongsTo('App\Models\Servers');
	}

	public function user()
	{
		return $this->belongsTo('App\User');
	}
}

app/Models/Owners.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Owners extends Model
{
	protected $table 	= 'owners';
	protected $fillable = ['nama_lengkap','email','no_hp'];

	
}

app/Models/Servers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Servers extends Model
{
	protected $table		= 'servers';
	protected $fillable 	= ['name_server','ip_address'];

	public function domains(){
		return $this->hasMany('App\Models\Domains');
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin','no_hp'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function domains(){
        return $this->hasMany('App\Models\Domains');
    }
}

app/Http/Controllers/Admin/DomainsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Servers;
use App\Models\Domains;
use App\User;
use Illuminate\Http\Request;

class DomainsController extends Controller
{
	public function index()
	{
		$domains 	= Domains::with(['server','user'])->get();
		// dd($domains);
		$servers 	= Servers::pluck('name_server','id');
		$owners 	= User::pluck('name','id');
		return view('admin.domains.index', compact('domains','servers','owners'));
	}

	public function store(Request $request)
	{
		$request->validate([
			'domain_name' 		=> 'required|unique:domains',
			'domain_expired' 	=> 'required',
			'server_id' 		=> 'required',
			'user_id' 			=> 'required'
		]);
		Domains::create($request->all());
		return redirect()->back()->with('success','Input Data Domain Successfully');
	}

	public function update(Request $request, $id)
	{
		$domain = Domains::find($id);
		$domain->update($request->all());
		return redirect()->back()->with('success','Update Data Domain Successfully');
	}

	public function destroy($id)
	{
		Domains::find($id)->delete();
		return redirect()->back()->with('success','Delete Data Domain Successfully');
	}
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
	public function adminHome()
	{
		return view('admin.dashboard');
	}
}

app/Http/Controllers/Admin/OwnersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class OwnersController extends Controller
{
	public function index()
	{
		$owners = User::all();
		return view('admin.owners.index', compact('owners'));
	}

	public function store(Request $request)
	{
		$request->validate([
			'name'		=> 'required|unique:users',
			'email'		=> 'required|email|unique:users',
			'password'	=> 'required|min:8',
			'no_hp'		=> 'required|min:10|max:13',
		]);
		$owner 						= User::create($request->all());
		$owner->password 			= Hash::make($request->password);
		$owner->is_admin 			= '0';
		$owner->remember_token 		= Str::random(15);
		$owner->email_verified_at 	= now();
		$owner->save();
		return redirect()->back()->with('success','Input Data Owner Successfully');
	}

	public function update(Request $request, $id)
	{
		$owner = User::find($id);
		if(is_null($request->password)){
			$owner->password 	= $owner->password;
		}else{
			$owner->password 	= Hash::make($request->password);
		}
		$owner->name = $request->name;
		$owner->email = $request->email;
		$owner->is_admin = $owner->is_admin;
		$owner->no_hp = $request->no_hp;
		$owner->save();
		return redirect()->back()->with('success','Update Data Owner Successfully');
	}

	public function destroy($id)
	{
		User::find($id)->delete();
		return redirect()->back()->with('success','Delete Data Owner Successfully');
	}
}

app/Http/Controllers/Admin/RuncloudController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use GuzzleHttp\Client;

class RuncloudController extends Controller
{
    public function index()
    {
    	$client = new Client([
    		'base_uri' => 'https://manage.runcloud.io/api/v2/',
    	]);
    	$a = $client->request('GET', '/get', ['auth' => ['rkd5LxNE56wVlMVHnWxIpX05PXyxrQhArtHdjuVlurZh', '4fCzVvFO6X4g7wuj4csrE0YuN5LEr5cGpxOULErEs5nxkwtys6cUp5Nekx584HGD']]);
    	dd($a);
    }
}

app/Http/Controllers/Admin/ServersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Servers;
use Illuminate\Http\Request;

class ServersController extends Controller
{
	public function index()
	{
		$servers = Servers::all();
		return view('admin.servers.index', compact('servers'));
	}

	public function store(Request $request)
	{
		$request->validate([
			'name_server' 	=> 'required|unique:servers',
			'ip_address' 	=> 'required|unique:servers'
		]);
		Servers::create($request->all());
		return redirect()->back()->with('success','Input Data Server Successfully');
	}

	public function update(Request $request, $id)
	{
		$server = Servers::find($id);
		$server->update($request->all());
		return redirect()->back()->with('success','Update Data Server Successfully');
	}

	public function destroy($id)
	{
		Servers::find($id)->delete();
		return redirect()->back()->with('success','Delete Data Server Successfully');
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    public function adminHome()
    {
        return view('admin.dashboard');
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app')

@section('app')
Dashboard
@endsection

@section('content')
<div class="container-fluid">
	<div class="panel panel-headline">
						<div class="panel-heading">
							<h3 class="panel-title">Weekly Overview</h3>
							<p class="panel-subtitle">Period: Oct 14, 2016 - Oct 21, 2016</p>
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-md-3">
									<div class="metric">
										<span class="icon"><i class="fa fa-download"></i></span>
										<p>
											<span class="number">1,252</span>
											<span class="title">Downloads</span>
										</p>
									</div>
								</div>
								<div class="col-md-3">
									<div class="metric">
										<span class="icon"><i class="fa fa-shopping-bag"></i></span>
										<p>
											<span class="number">203</span>
											<span class="title">Sales</span>
										</p>
									</div>
								</div>
								<div class="col-md-3">
									<div class="metric">
										<span class="icon"><i class="fa fa-eye"></i></span>
										<p>
											<span class="number">274,678</span>
											<span class="title">Visits</span>
										</p>
									</div>
								</div>
								<div class="col-md-3">
									<div class="metric">
										<span class="icon"><i class="fa fa-bar-chart"></i></span>
										<p>
											<span class="number">35%</span>
											<span class="title">Conversions</span>
										</p>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-9">
									<div id="headline-chart" class="ct-chart"></div>
								</div>
								<div class="col-md-3">
									<div class="weekly-summary text-right">
										<span class="number">2,315</span> <span class="percentage"><i class="fa fa-caret-up text-success"></i> 12%</span>
										<span class="info-label">Total Sales</span>
									</div>
									<div class="weekly-summary text-right">
										<span class="number">$5,758</span> <span class="percentage"><i class="fa fa-caret-up text-success"></i> 23%</span>
										<span class="info-label">Monthly Income</span>
									</div>
									<div class="weekly-summary text-right">
										<span class="number">$65,938</span> <span class="percentage"><i class="fa fa-caret-down text-danger"></i> 8%</span>
										<span class="info-label">Total Income</span>
									</div>
								</div>
							</div>
						</div>
					</div>
</div>
@endsection

resources/views/admin/domains/edit_delete.blade.php
<div class="demo-button">
	<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit_{{ $d->id }}">Edit</button>
	{{ Form::open(['route'=>['admin.domains.destroy',$d->id]]) }}
	@method('DELETE')
	<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
	{{ Form::close() }}
</div>

<!-- Modal -->
<div class="modal fade" id="edit_{{ $d->id }}" tabindex="-1" role="dialog" aria-labelledby="edit_{{ $d->id }}Label">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="edit_{{ $d->id }}Label">Edit {{ $d->name_server }}</h4>
			</div>
			{{ Form::model($d, ['route' => ['admin.domains.update', $d->id]]) }}
			@method('PATCH')
			<div class="modal-body">
				{{ Form::text('domain_name',$d->domain_name,['class'=>'form-control','placeholder'=>'Domain Name','id'=>'domain_name','style'=>'width: 100%;']) }}
				<br>
				<br>
				{{ Form::text('domain_expired',$d->domain_expired,['class'=>'form-control domain_expired','placeholder'=>'Domain Expired','id'=>'domain_expired','style'=>'width: 100%;']) }}
				<br>
				<br>
				{{ Form::select('server_id', $servers, $d->server_id, ['placeholder' => 'Select a Servers...','id'=>'server_id','style'=>'width: 100%;']) }}
				<br>
				<br>
				{{ Form::select('user_id', $owners, $d->user_id, ['placeholder' => 'Select a Owners...','id'=>'owner_id','style'=>'width: 100%;']) }}
				<br>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Update</button>
			</div>
			{{ Form::close() }}
		</div>
	</div>
</div>

resources/views/admin/domains/form_add.blade.php
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modalAddDomains">Add Data Domains</a>

<div class="modal fade" id="modalAddDomains" tabindex="-1" role="dialog" aria-labelledby="modalAddDomainsLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content text-left">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddDomainsLabel">Add Data</h4>
			</div>
			
			{{ Form::open(['route'=>'admin.domains.store']) }}
			<div class="modal-body">

				{{ Form::text('domain_name',old('domain_name'),['class'=>'form-control','placeholder'=>'Domain Name','id'=>'domain_name']) }}
				<br>
				{{ Form::text('domain_expired',old('domain_expired'),['class'=>'form-control','placeholder'=>'Domain Expired','id'=>'domain_expired']) }}
				<br>
				{{ Form::select('server_id', $servers, null, ['placeholder' => 'Select a Servers...','id'=>'server_id']) }}
				<br>
				{{ Form::select('user_id', $owners, null, ['placeholder' => 'Select a Owners...','id'=>'owner_id']) }}
				<br>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Save changes</button>
			</div>
			{{ Form::close() }}

		</div>
	</div>
</div>

resources/views/admin/domains/index.blade.php
@extends('admin.layouts.app')

@section('app')
Domains
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<!-- RECENT PURCHASES -->
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">Domains</h3>
					<div class="right">
						<button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
						<button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
					</div>
				</div>
				<div class="panel-body">
					<table class="table table-striped" id="domains-table" style="width:100%">
						<thead>
							<tr>
								<th>No.</th>
								<th>Domain Name</th>
								<th>Domain Expired</th>
								<th>Server Name</th>
								<th>Owner Name</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@php
							$no = 1;
							@endphp
							@foreach($domains as $d)
							<tr>
								<td>{{ $no++ }}</td>
								<td>{{ $d->domain_name }}</td>
								<td>{{ $d->domain_expired }}</td>
								<td>{{ $d->server->name_server }}</td>
								<td>{{ $d->user->name }}</td>
								<td>@include('admin.domains.edit_delete')</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="row">
						<div class="col-md-6">
							@if ($message = Session::get('success'))
								<div class="alert alert-success alert-dismissible" role="alert">
									<i class="fa fa-check-circle"></i>{{ $message }}
								</div>
							@endif
							@if ($errors->any())
							<div class="alert alert-danger alert-dismissible" role="alert">
								@foreach ($errors->all() as $error)
									<i class="fa fa-times-circle"></i>{{ $error }}<br/>
								@endforeach
							</div>
							@endif
						</div>

						<div class="col-md-6 text-right">
							@include('admin.domains.form_add')
						</div>
					</div>
				</div>
			</div>
			<!-- END RECENT PURCHASES -->
		</div>
	</div>
</div>
@endsection

@push('styles')
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
	<link rel="stylesheet" href="{{ asset('css/dt.css') }}">
	<link rel="stylesheet" href="{{ asset('css/s2.css') }}">
	<style>
		input.form-control.domain_expired.form-control.input {
			width: 100%;
		}
	</style>	
@endpush

@push('scripts')
	<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
	<script src="{{ asset('js/dt.js') }}"></script>
	<script src="{{ asset('js/s2.js') }}"></script>
	<script>
		flatpickr("#domain_expired",{
			altInput: true,
			altFormat: "F j, Y",
			dateFormat: "Y-m-d",
		});
		$(document).ready(function() {
			$('#domains-table').DataTable( {
				"order": [[ 1, "asc" ]]
			});
		} );
		$('#server_id').selectize();
		$('#owner_id').selectize();
	</script>
@endpush

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
	<title>@yield('app') | {{ config('app.name') }}</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	{{-- <link rel="stylesheet" href="assets/vendor/chartist/css/chartist-custom.css"> --}}
	<link rel="stylesheet" href="{{ asset('css/eFrd5.css') }}">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	@stack('styles')
</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		@include('admin.layouts.navbar')
		@include('admin.layouts.sidebar')
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				@yield('content')
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
		@include('admin.layouts.footer')
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{{ asset('js/eFrd5.js') }}"></script>
	@stack('scripts')
	{{-- <script src="assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
	<script src="assets/vendor/chartist/js/chartist.min.js"></script> --}}
</body>

</html>

resources/views/admin/layouts/footer.blade.php
<div class="clearfix"></div>
<footer>
	<div class="container-fluid">
		<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
	</div>
</footer>

resources/views/admin/layouts/navbar.blade.php
<!-- NAVBAR -->
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="brand" style="padding: 5px 10px;">
		<a href="index.html">
			<img src="{{ asset('img/logo.png') }}" alt="Klorofil Logo" class="img-responsive logo" width="35%">
		</a>
	</div>
	<div class="container-fluid">
		<div class="navbar-btn">
			<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
		</div>
		<div id="navbar-menu">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="https://www.gravatar.com/avatar/{{ auth()->user()->email }}?s=32&d=identicon&r=PG" class="img-circle" alt="Avatar"> <span>{{ auth()->user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
					<ul class="dropdown-menu">
						<li>
							<a href="{{ route('logout') }}"onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="lnr lnr-exit"></i> <span>{{ __('Logout') }}</span></a>
							<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
								@csrf
							</form>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
<!-- END NAVBAR -->

resources/views/admin/layouts/sidebar.blade.php
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar">
	<div class="sidebar-scroll">
		<nav>
			<ul class="nav">
				<li><a href="{{ route('admin.home') }}" class="{{ (request()->is('admin/dashboard')) ? 'active' : '' }}"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
				<li><a href="{{ route('admin.servers.index') }}" class="{{ (request()->is('admin/servers')) ? 'active' : '' }}"><i class="lnr lnr-rocket"></i> <span>Servers</span></a></li>
				<li><a href="{{ route('admin.domains.index') }}" class="{{ (request()->is('admin/domains')) ? 'active' : '' }}"><i class="lnr lnr-link"></i> <span>Domains</span></a></li>
				<li><a href="{{ route('admin.owners.index') }}" class="{{ (request()->is('admin/owners')) ? 'active' : '' }}"><i class="lnr lnr-users"></i> <span>Owners</span></a></li>
			</ul>
		</nav>
	</div>
</div>
<!-- END LEFT SIDEBAR -->

resources/views/admin/owners/edit_delete.blade.php
<div class="demo-button">
	<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit_{{ $ow->id }}">Edit</button>
	{{ Form::open(['route'=>['admin.owners.destroy',$ow->id]]) }}
	@method('DELETE')
	@if($ow->id == 1)
	<button type="button" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
	@else
	<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
	@endif
	{{ Form::close() }}
</div>

<!-- Modal -->
<div class="modal fade" id="edit_{{ $ow->id }}" tabindex="-1" role="dialog" aria-labelledby="edit_{{ $ow->id }}Label">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="edit_{{ $ow->id }}Label">Edit {{ $ow->nama_lengkap }}</h4>
			</div>
			{{ Form::model($ow, ['route' => ['admin.owners.update', $ow->id]]) }}
			@method('PATCH')
			<div class="modal-body">
				{{ Form::text('name',$ow->name,['class'=>'form-control','placeholder'=>'Nama Lengkap','style'=>'width: 100%;']) }}
				<br><br>
				{{ Form::number('no_hp',$ow->no_hp,['class'=>'form-control','placeholder'=>'No Hp','style'=>'width: 100%;']) }}
				<br><br>
				{{ Form::email('email',$ow->email,['class'=>'form-control','placeholder'=>'Email','style'=>'width: 100%;']) }}
				<br><br>
				{{ Form::password('password',['class'=>'form-control','placeholder'=>'Password','style'=>'width: 100%;']) }}
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Update</button>
			</div>
			{{ Form::close() }}
		</div>
	</div>
</div>

resources/views/admin/owners/form_add.blade.php
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#modalAddOwner">Add Data Owner</a>

<div class="modal fade" id="modalAddOwner" tabindex="-1" role="dialog" aria-labelledby="modalAddOwnerLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content text-left">
			
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalAddOwnerLabel">Add Data</h4>
			</div>
			
			{{ Form::open(['route'=>'admin.owners.store']) }}
			<div class="modal-body">
				{{ Form::text('name',old('name'),['class'=>'form-control','placeholder'=>'Nama Lengkap']) }}
				<br>
				{{ Form::number('no_hp',old('no_hp'),['class'=>'form-control','placeholder'=>'No Hp']) }}
				<br>
				{{ Form::email('email',old('email'),['class'=>'form-control','placeholder'=>'Email']) }}
				<br>
				{{ Form::password('password',['class'=>'form-control','placeholder'=>'Password']) }}
				<br>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Save changes</button>
			</div>
			{{ Form::close() }}

		</div>
	</div>
</div>

resources/views/admin/owners/index.blade.php
@extends('admin.layouts.app')

@section('app')
Owners
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<!-- RECENT PURCHASES -->
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">Owners</h3>
					<div class="right">
						<button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
						<button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
					</div>
				</div>
				<div class="panel-body">
					<table class="table table-striped" id="owners-table" style="width:100%">
						<thead>
							<tr>
								<th>No.</th>
								<th>Nama Lengkap</th>
								<th>Email</th>
								<th>No HP</th>
								<th>Status</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@php
							$no = 1;
							@endphp
							@foreach($owners as $ow)
							<tr>
								<td>{{ $no++ }}</td>
								<td>{{ $ow->name }}</td>
								<td>{{ $ow->email }}</td>
								<td>{{ $ow->no_hp }}</td>
								<td>
									@if($ow->is_admin == 1)
									<span class="label label-danger">Admin</span>
									@else
									<span class="label label-info">Site Owner</span>
									@endif
								</td>
								<td>@include('admin.owners.edit_delete')</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="row">
						<div class="col-md-6">
							@if ($message = Session::get('success'))
								<div class="alert alert-success alert-dismissible" role="alert">
									<i class="fa fa-check-circle"></i>{{ $message }}
								</div>
							@endif
							@if ($errors->any())
							<div class="alert alert-danger alert-dismissible" role="alert">
								@foreach ($errors->all() as $error)
									<i class="fa fa-times-circle"></i>{{ $error }}<br/>
								@endforeach
							</div>
							@endif
						</div>

						<div class="col-md-6 text-right">
							@include('admin.owners.form_add')
						</div>
					</div>
				</div>
			</div>
			<!-- END RECENT PURCHASES -->
		</div>
	</div>
</div>
@endsection

@push('styles')
	<link rel="stylesheet" href="{{ asset('css/dt.css') }}">
@endpush

@push('scripts')
	<script src="{{ asset('js/dt.js') }}"></script>
	<script>
		$(document).ready(function() {
			$('#owners-table').DataTable( {
				"order": [[ 0, "desc" ]]
			});
		} );
	</script>
@endpush